### PR TITLE
Update StandardModel.php

### PR DESCRIPTION
**Pull request by psfpro**
custom labels for columns
For exemples:
<pre><code>
$exporter = new Exporter([
            'query' => Device::find(),
            'filePath' => Yii::getAlias('@app/StatsExport.xlsx'),
            'sheetTitle' => 'Tests',
            'standardModelsConfig' => [
                [
                    'className' => Device::className(),
                    'extendStandardAttributes' => false,
                    'standardAttributesConfig' => [
                        [
                            'name' => 'user_id',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->user->name;
                            },
                            'label' => 'Name',
                        ],
                        [
                            'name' => 'user_id',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->user->surname;
                            },
                            'label' => 'Surname',
                        ],
                        [
                            'name' => 'user_id',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->user->email;
                            },
                            'label' => 'Email',
                        ],
                        [
                            'name' => 'identifier',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->identifier;
                            },
                            'label' => 'Device ID',
                        ],
                        [
                            'name' => 'juice_level',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->juice_level;
                            },
                            'label' => 'Juice level',
                        ],
                        [
                            'name' => 'updated',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->updated;
                            },
                            'label' => 'Updated',
                        ],
                    ],
                ],
            ],
        ]);
        $exporter->run();
</code></pre>

### CODE REVIEW

**Comment by arogachev** [comment]
What do you mean by that? Standard attributes list should be unique regardless of `extendStandardAttributes` option.

**Comment by psfpro** [comment]
When I make a custom field, I have no unique attributes.
For exemple attribute:  'name' => 'user_id'.
<pre>
                       [
                            'name' => 'user_id',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->user->name;
                            },
                            'label' => 'Name',
                        ],
                        [
                            'name' => 'user_id',
                            'valueReplacement' => function ($model) {
                                /* @var $model Device */
                                return $model->user->surname;
                            },
                            'label' => 'Surname',
                        ],
</pre>
What do you think about this? What other configuration options?

**Comment by arogachev** [comment]
To be honest, I was in hurry when writing exporter. I even didn't update the README with basic example of usage. 

The main problem is that used StandardModel is from import (see #6). It's better to use separate extended StandardModel for export, it will solve this problem.

You solution is OK, but it will also touch import.

If you need this urgently, you can use fork.

I will try to fix it as soon as possible.

**Comment by arogachev** [comment]
Fixed in b84f2eb. Use instead:

```php
[
    'name' => 'user_name',
    'label' => 'Name',
    'valueReplacement' => function ($model) {
        /* @var $model Device */
        return $model->user->name;
    },

],
[
    'name' => 'user_surname',
    'label' => 'Surname',
    'valueReplacement' => function ($model) {
        /* @var $model Device */
        return $model->user->surname;
    },
],
```

**Comment by arogachev** [comment]
Will update README soon.

**Pull request closed without merging**
